platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

target 'Washington' do


pod "Player", "~> 0.13.2"
pod 'SnapKitExtend'
pod 'Then'
pod 'Moya'
pod 'HandyJSON'
pod 'Kingfisher'
pod 'Reusable'
pod 'LLCycleScrollView'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'UINavigation-SXFixSpace'
# Player with default control layer.
pod 'SJVideoPlayer'

# The base player, without the control layer, can be used if you need a custom control layer.
pod 'SJBaseVideoPlayer'
end
